ERROR - 2024-05-21 00:51:17 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'db_incidencias' in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_incidencias', 3306, '', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'db_incidencias' in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
#7 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-21 00:51:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'db_incidencias'
[Method: GET, Route: oficinas]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-21 01:03:05 --> mysqli_sql_exception: Unknown column 'id_oficina' in 'order clause' in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-05-21 01:03:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_oficina' in 'order clause'
[Method: GET, Route: oficinas]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC', [], false)
 2 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 01:03:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_oficina' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC', [], false)
 4 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 01:03:05 --> [Caused by] mysqli_sql_exception: Unknown column 'id_oficina' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `oficinas`
ORDER BY `id_oficina` ASC', [], false)
 5 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Controller_oficinas.php(14): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 01:03:45 --> ParseError: syntax error, unexpected identifier "p", expecting "function" or "const"
[Method: GET, Route: perfiles]
in APPPATH\Controllers\Controller_perfiles.php on line 19.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp-8.2.12\\htdocs\\app_incidencias\\app\\Controllers\\Controller_perfiles.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Controller_perfiles')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Controller_perfiles')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Controller_perfiles', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 01:04:03 --> ParseError: syntax error, unexpected identifier "p", expecting "function" or "const"
[Method: GET, Route: perfiles]
in APPPATH\Controllers\Controller_perfiles.php on line 19.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp-8.2.12\\htdocs\\app_incidencias\\app\\Controllers\\Controller_perfiles.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Controller_perfiles')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Controller_perfiles')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Controller_perfiles', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-21 09:06:09 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`oficinas`, CONSTRAINT `oficinas_ibfk_1` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`)) in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `of...', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_oficinas.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_oficinas->guardar()
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-21 09:06:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`oficinas`, CONSTRAINT `oficinas_ibfk_1` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`))
[Method: POST, Route: oficinas/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (:nombre_oficina:, :id_estado:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Controller_oficinas.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->guardar()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 09:06:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`oficinas`, CONSTRAINT `oficinas_ibfk_1` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (\'Recursos humanos\', \'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (\'Recursos humanos\', \'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (:nombre_oficina:, :id_estado:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Controller_oficinas.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->guardar()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 09:06:09 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`oficinas`, CONSTRAINT `oficinas_ibfk_1` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (\'Recursos humanos\', \'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (\'Recursos humanos\', \'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (\'Recursos humanos\', \'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `oficinas` (`nombre_oficina`, `id_estado`) VALUES (:nombre_oficina:, :id_estado:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Controller_oficinas.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_oficinas->guardar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_oficinas))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-21 11:10:18 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`usuarios`, CONSTRAINT `usuarios_ibfk_3` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`)) in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert(Array)
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-21 11:10:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`usuarios`, CONSTRAINT `usuarios_ibfk_3` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`))
[Method: POST, Route: tecnicos/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:10:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`usuarios`, CONSTRAINT `usuarios_ibfk_3` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:10:18 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_incidencias`.`usuarios`, CONSTRAINT `usuarios_ibfk_3` FOREIGN KEY (`id_estado`) REFERENCES `estados` (`id_estado`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-21 11:11:08 --> mysqli_sql_exception: Column 'id_estado' cannot be null in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert(Array)
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-21 11:11:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_estado' cannot be null
[Method: POST, Route: tecnicos/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:, :id_estado:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:11:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_estado' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:, :id_estado:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:11:08 --> [Caused by] mysqli_sql_exception: Column 'id_estado' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:, :id_estado:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-21 11:12:20 --> mysqli_sql_exception: Column 'id_estado' cannot be null in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert(Array)
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-21 11:12:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_estado' cannot be null
[Method: POST, Route: tecnicos/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:, :id_estado:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:12:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_estado' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:, :id_estado:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:12:20 --> [Caused by] mysqli_sql_exception: Column 'id_estado' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (\'Aldo\', \'Pereda Loayza\', \'aldito@gmail.com\', \'12345\', \'1\', \'6\', NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombres`, `apellidos`, `correo`, `contrasenia`, `id_perfil`, `id_oficina`, `id_estado`) VALUES (:nombres:, :apellidos:, :correo:, :contrasenia:, :id_perfil:, :id_oficina:, :id_estado:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Controller_tecnicos.php(46): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->guardar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-21 11:20:42 --> mysqli_sql_exception: Illegal parameter data types int and row for operation '=' in C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp-8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp-8.2.12\htdocs\app_incidencias\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp-8.2.12\htdocs\app_incidencias\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp-8.2.12\htdocs\app_incidencias\app\Controllers\Controller_tecnicos.php(17): CodeIgniter\BaseModel->findAll()
#7 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->index()
#8 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
#9 C:\xampp-8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp-8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp-8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-05-21 11:20:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Illegal parameter data types int and row for operation '='
[Method: GET, Route: tecnicos]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `id_perfil` = :id_perfil:
ORDER BY `id_usuario` ASC', [...], false)
 2 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Controller_tecnicos.php(17): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:20:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Illegal parameter data types int and row for operation '='
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuarios`
WHERE `id_perfil` = (\'1\',\'Técnico\')
ORDER BY `id_usuario` ASC')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuarios`
WHERE `id_perfil` = (\'1\',\'Técnico\')
ORDER BY `id_usuario` ASC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `id_perfil` = :id_perfil:
ORDER BY `id_usuario` ASC', [...], false)
 4 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Controller_tecnicos.php(17): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-21 11:20:42 --> [Caused by] mysqli_sql_exception: Illegal parameter data types int and row for operation '='
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('SELECT *
FROM `usuarios`
WHERE `id_perfil` = (\'1\',\'Técnico\')
ORDER BY `id_usuario` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuarios`
WHERE `id_perfil` = (\'1\',\'Técnico\')
ORDER BY `id_usuario` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuarios`
WHERE `id_perfil` = (\'1\',\'Técnico\')
ORDER BY `id_usuario` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `id_perfil` = :id_perfil:
ORDER BY `id_usuario` ASC', [...], false)
 5 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Controller_tecnicos.php(17): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_tecnicos->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_tecnicos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
