CRITICAL - 2024-05-01 02:56:47 --> ParseError: syntax error, unexpected token "}", expecting ";"
[Method: GET, Route: areas]
in APPPATH\Controllers\Controller_areas.php on line 34.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Controllers\\Controller_areas.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Controller_areas')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Controller_areas')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Controller_areas', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-01 02:59:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp_8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp_8.2.12\htdocs\app_incidencias\app\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert(Array)
#8 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
#9 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
#10 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp_8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#3 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp_8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp_8.2.12\htdocs\app_incidencias\app\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert(Array)
#7 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
#8 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
#9 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp_8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-05-01 02:59:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: areas/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre`) VALUES (:nombre:)', [...], false)
 3 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-01 03:01:13 --> mysqli_sql_exception: Unknown column 'nombre' in 'field list' in C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp_8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp_8.2.12\htdocs\app_incidencias\app\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert(Array)
#8 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
#9 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
#10 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp_8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-01 03:01:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nombre' in 'field list'
[Method: POST, Route: areas/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre`) VALUES (:nombre:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 03:01:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nombre' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `areas` (`nombre`) VALUES (\'Administraci√≥n\')')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `areas` (`nombre`) VALUES (\'Administraci√≥n\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre`) VALUES (:nombre:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 03:01:13 --> [Caused by] mysqli_sql_exception: Unknown column 'nombre' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `areas` (`nombre`) VALUES (\'Administraci√≥n\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `areas` (`nombre`) VALUES (\'Administraci√≥n\')')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `areas` (`nombre`) VALUES (\'Administraci√≥n\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre`) VALUES (:nombre:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-01 03:04:56 --> mysqli_sql_exception: Column 'nombre_area' cannot be null in C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp_8.2.12\htdocs\app_incidencias\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp_8.2.12\htdocs\app_incidencias\app\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert(Array)
#8 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
#9 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
#10 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp_8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-01 03:04:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'nombre_area' cannot be null
[Method: POST, Route: areas/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre_area`) VALUES (:nombre_area:)', [...], false)
 2 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 03:04:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'nombre_area' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `areas` (`nombre_area`) VALUES (NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `areas` (`nombre_area`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre_area`) VALUES (:nombre_area:)', [...], false)
 4 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 03:04:56 --> [Caused by] mysqli_sql_exception: Column 'nombre_area' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `areas` (`nombre_area`) VALUES (NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `areas` (`nombre_area`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `areas` (`nombre_area`) VALUES (NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `areas` (`nombre_area`) VALUES (:nombre_area:)', [...], false)
 5 SYSTEMPATH\Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Controller_areas.php(32): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->guardar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-01 11:34:15 --> mysqli_sql_exception: Unknown column 'id_areas' in 'order clause' in C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\MySQLi\Connection.php(308): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp_8.2.12\htdocs\app_incidencias\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp_8.2.12\htdocs\app_incidencias\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp_8.2.12\htdocs\app_incidencias\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp_8.2.12\htdocs\app_incidencias\app\Controllers\Controller_areas.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(933): App\Controllers\Controller_areas->index()
#8 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
#9 C:\xampp_8.2.12\htdocs\app_incidencias\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp_8.2.12\htdocs\app_incidencias\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp_8.2.12\htdocs\app_incidencias\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-05-01 11:34:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_areas' in 'order clause'
[Method: GET, Route: areas]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC', [], false)
 2 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Controller_areas.php(14): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:34:15 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_areas' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC', [], false)
 4 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Controller_areas.php(14): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:34:15 --> [Caused by] mysqli_sql_exception: Unknown column 'id_areas' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `areas`
ORDER BY `id_areas` ASC', [], false)
 5 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Controller_areas.php(14): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:36:55 --> ErrorException: Undefined variable $areas
[Method: GET, Route: areas]
in APPPATH\Views\view_areas_listar.php on line 20.
 1 APPPATH\Views\view_areas_listar.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $areas', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_areas_listar.php', 20)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_areas_listar.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_areas_listar', [], true)
 5 APPPATH\Controllers\Controller_areas.php(17): view('view_areas_listar')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:37:35 --> ErrorException: Undefined variable $area
[Method: GET, Route: areas]
in APPPATH\Views\view_areas_listar.php on line 24.
 1 APPPATH\Views\view_areas_listar.php(24): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $area', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_areas_listar.php', 24)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_areas_listar.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_areas_listar', [], true)
 5 APPPATH\Controllers\Controller_areas.php(17): view('view_areas_listar', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_areas->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_areas))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:53:08 --> ErrorException: Undefined variable $active_areas
[Method: GET, Route: /]
in APPPATH\Views\view_template_header.php on line 29.
 1 APPPATH\Views\view_template_header.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $active_areas', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_template_header.php', 29)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_template_header.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_template_header', [], true)
 5 APPPATH\Controllers\Controller_incidencias.php(13): view('view_template_header')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_incidencias->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_incidencias))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:56:06 --> ErrorException: Undefined variable $active_areas
[Method: GET, Route: /]
in APPPATH\Views\view_template_header.php on line 29.
 1 APPPATH\Views\view_template_header.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $active_areas', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_template_header.php', 29)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_template_header.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_template_header', [], true)
 5 APPPATH\Controllers\Controller_incidencias.php(13): view('view_template_header')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_incidencias->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_incidencias))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 11:57:08 --> ErrorException: Undefined variable $active_areas
[Method: GET, Route: /]
in APPPATH\Views\view_template_header.php on line 29.
 1 APPPATH\Views\view_template_header.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $active_areas', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_template_header.php', 29)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_template_header.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_template_header', [], true)
 5 APPPATH\Controllers\Controller_incidencias.php(14): view('view_template_header', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_incidencias->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_incidencias))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 15:42:22 --> CodeIgniter\Database\Exceptions\DataException: There is no data to insert.
[Method: POST, Route: estados/guardar]
in SYSTEMPATH\BaseModel.php on line 826.
 1 SYSTEMPATH\BaseModel.php(826): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Controller_estados.php(34): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_estados->guardar()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_estados))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 15:50:19 --> ErrorException: Undefined variable $numero
[Method: GET, Route: estados]
in APPPATH\Views\view_estados_listar.php on line 19.
 1 APPPATH\Views\view_estados_listar.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $numero', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_estados_listar.php', 19)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_estados_listar.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_estados_listar', [], true)
 5 APPPATH\Controllers\Controller_estados.php(16): view('view_estados_listar', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_estados->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_estados))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 18:45:24 --> ErrorException: Undefined variable $variable
[Method: GET, Route: incidencias/crear]
in APPPATH\Views\view_incidencias_crear.php on line 41.
 1 APPPATH\Views\view_incidencias_crear.php(41): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $variable', 'C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_incidencias_crear.php', 41)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp_8.2.12\\htdocs\\app_incidencias\\app\\Views\\view_incidencias_crear.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('view_incidencias_crear', [], true)
 5 APPPATH\Controllers\Controller_incidencias.php(22): view('view_incidencias_crear', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_incidencias->crear()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_incidencias))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 21:58:50 --> CodeIgniter\Database\Exceptions\DataException: There is no data to insert.
[Method: POST, Route: incidencias/guardar]
in SYSTEMPATH\BaseModel.php on line 826.
 1 SYSTEMPATH\BaseModel.php(826): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Controller_incidencias.php(32): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_incidencias->guardar()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_incidencias))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-01 22:03:00 --> CodeIgniter\Database\Exceptions\DataException: There is no data to insert.
[Method: POST, Route: incidencias/guardar]
in SYSTEMPATH\BaseModel.php on line 826.
 1 SYSTEMPATH\BaseModel.php(826): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(791): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Controller_incidencias.php(33): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Controller_incidencias->guardar()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controller_incidencias))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
